# Configured for Apple Silicon support

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "${OLLAMA_PORT:-11434}:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ${PWD}/models:/models
# Using CPU by default on macOS
    restart: unless-stopped
    networks:
      - rag-network
# Removed healthcheck to improve compatibility

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: chromadb
    volumes:
      - chroma_data:/chroma/chroma
    ports:
      - "${CHROMA_PORT:-8000}:8000"
    environment:
      - ALLOW_RESET=true
    restart: unless-stopped
    networks:
      - rag-network
# Removed healthcheck to improve compatibility

  rag-app:
    build:
      context: ./rag-app
      dockerfile: Dockerfile
    container_name: rag-app
    ports:
      - "${APP_PORT:-8501}:8501"
    depends_on:
      - ollama
      - chroma
    volumes:
      - ${PWD}/data:/app/data
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - CHROMA_HOST=http://chroma:8000
      - EMBEDDING_MODEL=${EMBEDDING_MODEL:-nomic-embed-text}
      - DEFAULT_MODEL=${DEFAULT_MODEL:-llama3}
      - PERSIST_DIRECTORY=/app/data/chroma_db
    restart: unless-stopped
    networks:
      - rag-network

networks:
  rag-network:
    driver: bridge

volumes:
  ollama_data:
  chroma_data:
